stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "Déploiement sur GitLab Pages"
    - mkdir .public 
    - cp -r * .public/
    - mv .public/ public
  artifacts:
    paths:
      - public
  only:
    - master
