stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "Déploiement sur GitLab Pages"
    - mkdir public || true
    - cp -r * public/
  artifacts:
    paths:
      - public
  only:
    - master
